print ("hello")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")

print("I am bored again"
  
print("I am bored again"    
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bore
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")d again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")  
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")    
print("I am bored again"
print(" NOTHING Special here")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again")
print("I am bored again")
      print("I am bored again")
print("I am bored again")

print("I am bored again")
